# /onfig/application.yml

development:
  lti_base_url: "http://152.7.177.3:8080"
  moodle_base_url: "http://152.7.177.192"
  LTI_CONSUMER_KEY: "123456"
  LTI_SHARED_ENCODER: "123456"
  LTI_TOOL_URL: "http://152.7.177.192"

test:
  lti_base_url: "https://expertiza.ncsu.edu/"
  moodle_base_url: "http://wolfware.ncsu.edu"
  LTI_CONSUMER_KEY: "123456"
  LTI_SHARED_ENCODER: "123456"
  LTI_TOOL_URL: "http://152.7.177.192"
  
production:
  lti_base_url: "https://expertiza.ncsu.edu/"
  moodle_base_url: "http://wolfware.ncsu.edu"
  LTI_CONSUMER_KEY: <%= ENV["LTI_CONSUMER_KEY"] %>
  LTI_SHARED_ENCODER: <%= ENV["LTI_SHARED_SECRET"] %>
  LTI_TOOL_URL: "https://wolfware.ncsu.edu"
